In [3]:
import pandas as pd
import numpy as np

tweets_depresivos_df = pd.DataFrame(pd.read_excel("Extraccion_Tweets/Dataset_depresivo_limpieza_manual.xlsx")) 

tweets_depresivos_df.head()

,id,conversation_id,created_at,date,time,timezone,user_id,username,name,place,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1.339913e+18,1.339913e+18,"2020-12-18 07:37:28 Hora est. Pacífico, Sudamé...",2020-12-18,07:37:28,-500,1558953666,johasolano27,Joha Solano♥️,NaN,...,"-1.3695361279507605,-78.08139447223985,27.9857...",NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
1,1.369100e+18,1.369100e+18,"2021-03-08 20:35:50 Hora est. Pacífico, Sudamé...",2021-03-08,20:35:50,-500,64263405,estebanacostab,esteban acosta,NaN,...,"-1.3695361279507605,-78.08139447223985,27.9857...",NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
2,1.401985e+18,1.401985e+18,"2021-06-07 14:32:44 Hora est. Pacífico, Sudamé...",2021-06-07,14:32:44,-500,1242893257555824896,librasequilibra,Mel ♎️,NaN,...,"-1.3695361279507605,-78.08139447223985,27.9857...",NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
3,1.396149e+18,1.396149e+18,"2021-05-22 12:00:49 Hora est. Pacífico, Sudamé...",2021-05-22,12:00:49,-500,1242893257555824896,librasequilibra,Mel ♎️,NaN,...,"-1.3695361279507605,-78.08139447223985,27.9857...",NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
4,1.373680e+18,1.373680e+18,"2021-03-21 11:56:55 Hora est. Pacífico, Sudamé...",2021-03-21,11:56:55,-500,75320297,flakissguevara,Andrea Guevara,NaN,...,"-1.3695361279507605,-78.08139447223985,27.9857...",NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN

In [4]:
#eliminamos los atributos que no son de utildad
tweets_depresivos_df.drop(['conversation_id', 'created_at', 'timezone', 'user_id', 'username', 'name', 'place', 'source', 'user_rt_id', 'user_rt', 'retweet_id', 'reply_to', 'retweet_date', 'translate', 'trans_src', 'trans_dest', 'language', 'mentions', 'urls', 'photos', 'replies_count', 'retweets_count', 'likes_count', 'hashtags', 'cashtags', 'link', 'retweet', 'quote_url', 'video', 'thumbnail', 'near', 'geo'], axis = 1, inplace = True)
tweets_depresivos_df.head()
tweets_depresivos_df = tweets_depresivos_df.drop_duplicates()

In [6]:
tweets_depresivos_df = tweets_depresivos_df.sample(frac=1)
tweets_depresivos_df.to_excel('TweetsDepresivosValidacionPSIC.xlsx', index=False)